name: The main GitHub Actions for testing pr

on:
  pull_request:
    branches:
      - main
      - master
      - develop

permissions:
  contents: read
  pull-requests: write


jobs:
  golangci:
    runs-on: ubuntu-latest
    name: Проверка кода линтером
    steps:
      - &checkout
        name: Копирование кода в раннер
        uses: actions/checkout@v4
      - name: Подготовка среды
        uses: ./.github/actions/setup
      - name: Проверка линтером
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_version: v2.1.0
          golangci_lint_flags: --timeout=5m
          reporter: github-pr-review
          filter_mode: diff_context
          level: warning
          fail_level: warning
      - name: Дожим репозитория (на дивы попадают не все проверки)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1


  try-build:
    needs:
      - golangci
    name: Сборка приложения
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - *checkout
      - name: Подготовка среды
        uses: ./.github/actions/setup
      - name: Попытка собрать приложение
        run: go build -v ./... -o /dev/null

  unit-tests:
    needs:
      - try-build
    name: Запуск unit-тестов
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - *checkout
      - name: Подготовка среды
        uses: ./.github/actions/setup
      - name: Запуск Unit-тестов
        run: go test ./...
      - name: Проверка на состояние гонки
        run: go test --race ./...