name: The main GitHub Actions for testing pr

on:
  pull_request:
    branches:
      - main
      - master
      - develop

env:
  working-directory: './services/simple-http-server/src'

jobs:
  golangci:
    runs-on: ubuntu-latest
    name: Проверка кода линтером
    permissions:
      checks: write
      discussions: write
      pull-requests: write
      contents: read
    steps:
      - &checkout
        name: Копирование кода в раннер
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Подготовка среды
        uses: ./.github/actions/setup
      - name: Проверка линтером
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_version: v2.1.0
          golangci_lint_flags: --timeout=5m
          reporter: github-pr-review
          filter_mode: diff_context
          level: warning
          fail_level: warning
          cache: true
          workdir: ${{env.working-directory}}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Дожим репозитория (на дивы попадают не все проверки)
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: "goinstall"
          working-directory: ${{env.working-directory}}



  try-build:
    needs:
      - golangci
    name: Сборка приложения
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - name: Подготовка среды
        uses: ./.github/actions/setup
      - name: Попытка собрать приложение
        run: go build -o deleteme .
        working-directory: ${{env.working-directory}}
      - name: Удаление артефакта
        run: rm deleteme
        working-directory: ${{env.working-directory}}

  unit-tests:
    needs:
      - try-build
    name: Запуск unit-тестов
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - *checkout
      - name: Подготовка среды
        uses: ./.github/actions/setup
      - name: Запуск Unit-тестов
        run: go test ./...
        working-directory: ${{env.working-directory}}
      - name: Проверка на состояние гонкb
        run: go test --race ./...
        working-directory: ${{env.working-directory}}